// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.xxx.doub.remoting.exchange.protobuf;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:doub.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional .doub.Request.EventType eventType = 2;</code>
     */
    boolean hasEventType();
    /**
     * <code>optional .doub.Request.EventType eventType = 2;</code>
     */
    com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType getEventType();

    /**
     * <code>optional .doub.Request.File file = 3;</code>
     */
    boolean hasFile();
    /**
     * <code>optional .doub.Request.File file = 3;</code>
     */
    com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File getFile();
    /**
     * <code>optional .doub.Request.File file = 3;</code>
     */
    com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder getFileOrBuilder();

    /**
     * <code>optional .doub.Request.Message message = 4;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional .doub.Request.Message message = 4;</code>
     */
    com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message getMessage();
    /**
     * <code>optional .doub.Request.Message message = 4;</code>
     */
    com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code doub.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:doub.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType value = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                eventType_ = value;
              }
              break;
            }
            case 26: {
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = file_.toBuilder();
              }
              file_ = input.readMessage(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(file_);
                file_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.class, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code doub.Request.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MESSAGE = 0;</code>
       */
      MESSAGE(0, 0),
      /**
       * <code>FILE = 1;</code>
       */
      FILE(1, 1),
      ;

      /**
       * <code>MESSAGE = 0;</code>
       */
      public static final int MESSAGE_VALUE = 0;
      /**
       * <code>FILE = 1;</code>
       */
      public static final int FILE_VALUE = 1;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return MESSAGE;
          case 1: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:doub.Request.EventType)
    }

    public interface FileOrBuilder extends
        // @@protoc_insertion_point(interface_extends:doub.Request.File)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bytes data = 1;</code>
       */
      boolean hasData();
      /**
       * <code>optional bytes data = 1;</code>
       */
      com.google.protobuf.ByteString getData();

      /**
       * <code>optional string fileType = 2;</code>
       */
      boolean hasFileType();
      /**
       * <code>optional string fileType = 2;</code>
       */
      java.lang.String getFileType();
      /**
       * <code>optional string fileType = 2;</code>
       */
      com.google.protobuf.ByteString
          getFileTypeBytes();

      /**
       * <code>optional int64 fileLength = 3;</code>
       */
      boolean hasFileLength();
      /**
       * <code>optional int64 fileLength = 3;</code>
       */
      long getFileLength();
    }
    /**
     * Protobuf type {@code doub.Request.File}
     */
    public static final class File extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:doub.Request.File)
        FileOrBuilder {
      // Use File.newBuilder() to construct.
      private File(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private File(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final File defaultInstance;
      public static File getDefaultInstance() {
        return defaultInstance;
      }

      public File getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private File(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                data_ = input.readBytes();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                fileType_ = bs;
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                fileLength_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_File_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.class, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder.class);
      }

      public static com.google.protobuf.Parser<File> PARSER =
          new com.google.protobuf.AbstractParser<File>() {
        public File parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new File(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<File> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DATA_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>optional bytes data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      public static final int FILETYPE_FIELD_NUMBER = 2;
      private java.lang.Object fileType_;
      /**
       * <code>optional string fileType = 2;</code>
       */
      public boolean hasFileType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string fileType = 2;</code>
       */
      public java.lang.String getFileType() {
        java.lang.Object ref = fileType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string fileType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        java.lang.Object ref = fileType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int FILELENGTH_FIELD_NUMBER = 3;
      private long fileLength_;
      /**
       * <code>optional int64 fileLength = 3;</code>
       */
      public boolean hasFileLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 fileLength = 3;</code>
       */
      public long getFileLength() {
        return fileLength_;
      }

      private void initFields() {
        data_ = com.google.protobuf.ByteString.EMPTY;
        fileType_ = "";
        fileLength_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, data_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getFileTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, fileLength_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, data_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getFileTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, fileLength_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code doub.Request.File}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:doub.Request.File)
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_File_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_File_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.class, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder.class);
        }

        // Construct using com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          data_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          fileType_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          fileLength_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_File_descriptor;
        }

        public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File getDefaultInstanceForType() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance();
        }

        public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File build() {
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File buildPartial() {
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File result = new com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.data_ = data_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.fileType_ = fileType_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.fileLength_ = fileLength_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File) {
            return mergeFrom((com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File other) {
          if (other == com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance()) return this;
          if (other.hasData()) {
            setData(other.getData());
          }
          if (other.hasFileType()) {
            bitField0_ |= 0x00000002;
            fileType_ = other.fileType_;
            onChanged();
          }
          if (other.hasFileLength()) {
            setFileLength(other.getFileLength());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes data = 1;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional bytes data = 1;</code>
         */
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>optional bytes data = 1;</code>
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes data = 1;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000001);
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }

        private java.lang.Object fileType_ = "";
        /**
         * <code>optional string fileType = 2;</code>
         */
        public boolean hasFileType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string fileType = 2;</code>
         */
        public java.lang.String getFileType() {
          java.lang.Object ref = fileType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              fileType_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string fileType = 2;</code>
         */
        public com.google.protobuf.ByteString
            getFileTypeBytes() {
          java.lang.Object ref = fileType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fileType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string fileType = 2;</code>
         */
        public Builder setFileType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          fileType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string fileType = 2;</code>
         */
        public Builder clearFileType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          fileType_ = getDefaultInstance().getFileType();
          onChanged();
          return this;
        }
        /**
         * <code>optional string fileType = 2;</code>
         */
        public Builder setFileTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          fileType_ = value;
          onChanged();
          return this;
        }

        private long fileLength_ ;
        /**
         * <code>optional int64 fileLength = 3;</code>
         */
        public boolean hasFileLength() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 fileLength = 3;</code>
         */
        public long getFileLength() {
          return fileLength_;
        }
        /**
         * <code>optional int64 fileLength = 3;</code>
         */
        public Builder setFileLength(long value) {
          bitField0_ |= 0x00000004;
          fileLength_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 fileLength = 3;</code>
         */
        public Builder clearFileLength() {
          bitField0_ = (bitField0_ & ~0x00000004);
          fileLength_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:doub.Request.File)
      }

      static {
        defaultInstance = new File(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:doub.Request.File)
    }

    public interface MessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:doub.Request.Message)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string data = 1;</code>
       */
      boolean hasData();
      /**
       * <code>optional string data = 1;</code>
       */
      java.lang.String getData();
      /**
       * <code>optional string data = 1;</code>
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * Protobuf type {@code doub.Request.Message}
     */
    public static final class Message extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:doub.Request.Message)
        MessageOrBuilder {
      // Use Message.newBuilder() to construct.
      private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Message defaultInstance;
      public static Message getDefaultInstance() {
        return defaultInstance;
      }

      public Message getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Message(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                data_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.class, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder.class);
      }

      public static com.google.protobuf.Parser<Message> PARSER =
          new com.google.protobuf.AbstractParser<Message>() {
        public Message parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Message> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DATA_FIELD_NUMBER = 1;
      private java.lang.Object data_;
      /**
       * <code>optional string data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        data_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getDataBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getDataBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code doub.Request.Message}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:doub.Request.Message)
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_Message_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_Message_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.class, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder.class);
        }

        // Construct using com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          data_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_Message_descriptor;
        }

        public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message getDefaultInstanceForType() {
          return com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance();
        }

        public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message build() {
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message buildPartial() {
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message result = new com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.data_ = data_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message) {
            return mergeFrom((com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message other) {
          if (other == com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance()) return this;
          if (other.hasData()) {
            bitField0_ |= 0x00000001;
            data_ = other.data_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object data_ = "";
        /**
         * <code>optional string data = 1;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string data = 1;</code>
         */
        public java.lang.String getData() {
          java.lang.Object ref = data_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              data_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string data = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          java.lang.Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string data = 1;</code>
         */
        public Builder setData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string data = 1;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000001);
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <code>optional string data = 1;</code>
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          data_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:doub.Request.Message)
      }

      static {
        defaultInstance = new Message(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:doub.Request.Message)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 2;
    private com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType eventType_;
    /**
     * <code>optional .doub.Request.EventType eventType = 2;</code>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .doub.Request.EventType eventType = 2;</code>
     */
    public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType getEventType() {
      return eventType_;
    }

    public static final int FILE_FIELD_NUMBER = 3;
    private com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File file_;
    /**
     * <code>optional .doub.Request.File file = 3;</code>
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .doub.Request.File file = 3;</code>
     */
    public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File getFile() {
      return file_;
    }
    /**
     * <code>optional .doub.Request.File file = 3;</code>
     */
    public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder getFileOrBuilder() {
      return file_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message message_;
    /**
     * <code>optional .doub.Request.Message message = 4;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .doub.Request.Message message = 4;</code>
     */
    public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message getMessage() {
      return message_;
    }
    /**
     * <code>optional .doub.Request.Message message = 4;</code>
     */
    public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder getMessageOrBuilder() {
      return message_;
    }

    private void initFields() {
      id_ = 0;
      eventType_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType.MESSAGE;
      file_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance();
      message_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, file_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, file_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code doub.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:doub.Request)
        com.xxx.doub.remoting.exchange.protobuf.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.class, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Builder.class);
      }

      // Construct using com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFileFieldBuilder();
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType.MESSAGE;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fileBuilder_ == null) {
          file_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance();
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (messageBuilder_ == null) {
          message_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.internal_static_doub_Request_descriptor;
      }

      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request getDefaultInstanceForType() {
        return com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.getDefaultInstance();
      }

      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request build() {
        com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request buildPartial() {
        com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request result = new com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (fileBuilder_ == null) {
          result.file_ = file_;
        } else {
          result.file_ = fileBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request) {
          return mergeFrom((com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request other) {
        if (other == com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasFile()) {
          mergeFile(other.getFile());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType eventType_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType.MESSAGE;
      /**
       * <code>optional .doub.Request.EventType eventType = 2;</code>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .doub.Request.EventType eventType = 2;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType getEventType() {
        return eventType_;
      }
      /**
       * <code>optional .doub.Request.EventType eventType = 2;</code>
       */
      public Builder setEventType(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .doub.Request.EventType eventType = 2;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        eventType_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.EventType.MESSAGE;
        onChanged();
        return this;
      }

      private com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File file_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder> fileBuilder_;
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public boolean hasFile() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File getFile() {
        if (fileBuilder_ == null) {
          return file_;
        } else {
          return fileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public Builder setFile(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          file_ = value;
          onChanged();
        } else {
          fileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public Builder setFile(
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          file_ = builderForValue.build();
          onChanged();
        } else {
          fileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public Builder mergeFile(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File value) {
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              file_ != com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance()) {
            file_ =
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.newBuilder(file_).mergeFrom(value).buildPartial();
          } else {
            file_ = value;
          }
          onChanged();
        } else {
          fileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.getDefaultInstance();
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder getFileBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder getFileOrBuilder() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilder();
        } else {
          return file_;
        }
      }
      /**
       * <code>optional .doub.Request.File file = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.File.Builder, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.FileOrBuilder>(
                  getFile(),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }

      private com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message message_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder> messageBuilder_;
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message getMessage() {
        if (messageBuilder_ == null) {
          return message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public Builder setMessage(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public Builder setMessage(
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public Builder mergeMessage(com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              message_ != com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance()) {
            message_ =
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.getDefaultInstance();
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder getMessageBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      public com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_;
        }
      }
      /**
       * <code>optional .doub.Request.Message message = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.Message.Builder, com.xxx.doub.remoting.exchange.protobuf.RequestProto.Request.MessageOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:doub.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:doub.Request)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doub_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doub_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doub_Request_File_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doub_Request_File_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doub_Request_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doub_Request_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\004doub\"\204\002\n\007Request\022\n\n\002id\030" +
      "\001 \002(\005\022*\n\teventType\030\002 \001(\0162\027.doub.Request." +
      "EventType\022 \n\004file\030\003 \001(\0132\022.doub.Request.F" +
      "ile\022&\n\007message\030\004 \001(\0132\025.doub.Request.Mess" +
      "age\032:\n\004File\022\014\n\004data\030\001 \001(\014\022\020\n\010fileType\030\002 " +
      "\001(\t\022\022\n\nfileLength\030\003 \001(\003\032\027\n\007Message\022\014\n\004da" +
      "ta\030\001 \001(\t\"\"\n\tEventType\022\013\n\007MESSAGE\020\000\022\010\n\004FI" +
      "LE\020\001B7\n\'com.xxx.doub.remoting.exchange.p" +
      "rotobufB\014RequestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_doub_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doub_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_doub_Request_descriptor,
        new java.lang.String[] { "Id", "EventType", "File", "Message", });
    internal_static_doub_Request_File_descriptor =
      internal_static_doub_Request_descriptor.getNestedTypes().get(0);
    internal_static_doub_Request_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_doub_Request_File_descriptor,
        new java.lang.String[] { "Data", "FileType", "FileLength", });
    internal_static_doub_Request_Message_descriptor =
      internal_static_doub_Request_descriptor.getNestedTypes().get(1);
    internal_static_doub_Request_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_doub_Request_Message_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
